movies/accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name = 'accounts/login.html'),name='login'),
    path('logout/', auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',views.SignUp.as_view(),name='signup'),
]

movies/crud_app/urls.py
from django.urls import re_path, path, include
from . import views

app_name = 'crup_app'

urlpatterns = [
    path('',views.MoviesList.as_view(),name='all'),
    path('new/', views.CreateMovie.as_view(),name='create'),
    path('search/', views.searching, name='search'),
    re_path(r'^movie/(?P<pk>\d+)/$', views.MovieDetail.as_view(), name='detail'),
    re_path(r'^delete/(?P<pk>\d+)/$',views.DeleteClient.as_view(),name='delete'),
    re_path(r'^edit/(?P<pk>\d+)/$',views.ClientUpdate.as_view(),name='movie_edit'),
    re_path(r'^movie/(?P<pk>\d+)/recommend/$', views.AddRecommend.as_view(),name='add_recommend'),
]

movies/movies/urls.py
from django.contrib import admin
from django.urls import re_path, path, include
from. import views
from crud_app.models import Movies
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets

class MoviesSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = Movies
        fields = ['name', 'director', 'gener']

class MoviesViewSet(viewsets.ModelViewSet):
    queryset = Movies.objects.all()
    serializer_class = MoviesSerializer

router = routers.DefaultRouter()
router.register(r'movies', MoviesViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(), name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('movies/', include('crud_app.urls',namespace='crud_app')),
    re_path(r'^api-auth/', include('rest_framework.urls')),
]

movies/accounts/models.py
from django.db import models
from django.contrib import auth

# Create your models here.
class User(auth.models.User, auth.models.PermissionsMixin):

    def __str__(self):
        return "@{}".format(self.username)

movies/crud_app/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.db.models import Q

from django.contrib.auth import get_user_model
User = get_user_model()

class Movies(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.TextField(max_length=80)
    slug = models.SlugField(allow_unicode=True,unique=True)
    gener = models.TextField(max_length=80)
    director = models.TextField(max_length=80)
    description = models.TextField()
    recommendations = models.ManyToManyField(User, related_name='recommendations_for_user', through='RecommendationUser')

    def __str__(self):
        return self.name

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('crud_app:detail',kwargs={'pk':self.pk})

    class Meta:
        ordering = ['name']

class RecommendationUser(models.Model):
    movie = models.ForeignKey(Movies, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('movie','user')

movies/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreationForm(UserCreationForm):

    class Meta:
        fields = ('username', 'email', 'password1','password2')
        model = get_user_model()

movies/accounts/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from . import forms
# Create your views here.

class SignUp(CreateView):
    form_class = forms.UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

movies/crud_app/views.py
from django.shortcuts import render
from django.urls import reverse

from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views import generic
from django.db.models import Q
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.db import IntegrityError

from django.contrib.auth.decorators import login_required

from . import models

class MoviesList(LoginRequiredMixin, generic.ListView):
    model = models.Movies

class CreateMovie(LoginRequiredMixin, generic.CreateView):
    redirect_field_name = 'crud_app/movie_detail.html'
    fields = ('name','description','gener','director')
    model = models.Movies

    def form_valid(self,form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class MovieDetail(generic.DetailView):
    model = models.Movies

class DeleteClient(LoginRequiredMixin,generic.DeleteView):
    model = models.Movies
    success_url = reverse_lazy('crud_app:all')

class ClientUpdate(LoginRequiredMixin, generic.UpdateView):
    redirect_field_name = 'crud_app/movie_detail.html'
    model = models.Movies
    fields = ['name','description','gener','director']
    template_name_suffix = '_update_form'

class AddRecommend(LoginRequiredMixin,generic.RedirectView):

    def get_redirect_url(self,*args,**kwargs):
        return reverse('crud_app:detail', kwargs={'pk':self.kwargs.get('pk')})

    def get(self,request,*args,**kwargs):

        movie = get_object_or_404(models.Movies, pk=self.kwargs.get('pk'))

        try:
            models.RecommendationUser.objects.create(user=self.request.user,movie=movie)
        except IntegrityError:
            messages.warning(self.request, 'Warning already recommend!')
        else:
            messages.success(self.request,'You now recommend the movie!')

        return super().get(request,*args,**kwargs)

################################################################################

def searching(request):

    q = request.GET.get('q', '')

    querys = (Q(name__icontains=q))

    movies_s = models.Movies.objects.filter(querys)

    return render(request, 'search.html', {'movies_s': movies_s})

movies/movies/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
# Create your views here.

class HomePage(TemplateView):
    template_name = 'index.html'
    
class TestPage(TemplateView):
    template_name = 'test.html'

class ThanksPage(TemplateView):
    template_name = 'thanks.html'

movies/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
  <h1>
    <div class="register-title">
      Log In
    </div>
  </h1>
  <form action="{% url 'login' %}" method="POST" class="register">
    {% csrf_token %}
    <input type="text" name='username' class="register-input" id="id_username" placeholder="Usuario">
    <input type="password" name='password' class="register-input" id="id_password" placeholder="Contraseña">
    <input type="submit" class="btn register-button" value="Ingresar">
  </form>
{% endblock %}

movies/accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% block content %}
  <h1>
    <div class="big-title">
      Sign Up
    </div>
  </h1>
  <form method="POST" class="big-form">
    {% csrf_token %}
    <input type="text" name='username' class="register-input" id="id_username" placeholder="Username">
    <div class="help-block">
      Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
    </div>
    <input type="email" name='email' class="register-input" id="id_email" placeholder="Email">
    <input type="password" name='password1' class="register-input" id="id_password1" placeholder="Password">
    <div class="help-block">
      <ul>
        <li>Your password can't be too similar to your other personal information.</li>
        <li>Your password must contain at least 8 characters.</li>
        <li>Your password can't be a commonly used password.</li>
        <li>Your password can't be entirely numeric.</li>
      </ul>
    </div>
    <input type="password" name='password2' class="register-input" id="id_password2" placeholder="Confirm Password">
    <div class="help-block">Enter the same password as before, for verification.</div>
    <input type="submit" class="btn register-button" value="Register">
  </form>
{% endblock %}

movies/crud_app/templates/crud_app/movies_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<form method="POST">
  {% csrf_token %}
  <h2>Are you sure you want to delete {{ movies.name }}?</h2>
  <input type="submit" class='btn btn-danger' value="Confirm">
  <a href="{% url 'crud_app:detail' pk=movies.pk %}" class="btn btn-secondary btn-large">Cancel</a>
</form>
{% endblock %}

movies/crud_app/templates/crud_app/movies_detail.html
{% extends "base.html" %}

{% block content %}

<div class="card border-success mb-3 text-center">
  <div class="card-header border-success">
    <h3>{{ movies.name }}</h3>
    <h6 class="text-muted">Recommendations: {{ movies.recommendations.count }}</h6>
  </div>
  <div class="card-body">
    <h5 class="card-title">By: {{ movies.user.username }}</h5>
    <p class="card-text">{{ movies.description }}</p>
    {% if user in movies.recommendations.all %}

    {% else %}
      <a href="{% url 'crud_app:add_recommend' pk=movies.pk %}" title="recommend" class="btn btn-primary btn-sm">
        Recommend
      </a>
    {% endif %}
  </div>
  <div class="card-footer border-success">
    <p>Gener: {{ movies.gener }}</p>
    <p>Director: {{ movies.director }}</p>
  </div>
</div>

{% endblock %}

movies/crud_app/templates/crud_app/movies_form.html
{% extends "base.html" %}

{% block content %}

<h1>
  <div class="big-title">
    Create a new movie
  </div>
</h1>
<form class='big-form' action="{% url 'crud_app:create' %}" method="POST">
  {% csrf_token %}
  <input type="text" name='name' class='register-input' id="id_name" placeholder="Name">
  <textarea name="description" id="id_description" placeholder="Description" rows="8" cols="80"></textarea>
  <input type="text" name='gener' class='register-input' id="id_gener" placeholder="Gener">
  <input type="text" name='director' class='register-input' id="id_director" placeholder="Director">
  <input type="submit" value="Add" class='register-button' class="btn btn-primary btn-large">
</form>

{% endblock %}

movies/crud_app/templates/crud_app/movies_list.html
{% extends "base.html" %}

{% block content %}

<div class="accordion" id="accordionExec">
  {% for movie in movies_list %}
    <div class="card border-info">
      <div class="card-header border-warning" id="heading{{movie.pk}}">
        <form>
          <div class="form-inline">
            <h2 class="mb-0 col-sm-8">
              <button class="btn btn-link text-info" type="button" data-toggle="collapse" data-target="#collapse{{movie.pk}}" aria-expanded="false" aria-controls="collapse{{movie.pk}}">
                {{ movie.name }}
              </button>
            </h2>
            <div class="col-sm-1 mb-1">
            </div>
          </div>
        </form>
      </div>
      <div id="collapse{{movie.pk}}" class="collapse" aria-labelledby="heading{{movie.pk}}" data-parent="#accordionExec">
        <div class="card-body text-info">
          <form>
            <div class="form-inline">
              <div class="col-sm-9">
                {{ movie.description }}
              </div>
              <div class="col-sm-1 mb-1">
                <a href="{% url 'crud_app:detail' pk=movie.pk %}" title="detail" class="btn btn-outline-success btn-sm">
                  Detail
                </a>
              </div>
              <div class="col-sm-1 mb-1">
                <a href="{% url 'crud_app:movie_edit' pk=movie.pk %}" title="update" class="btn btn-outline-primary btn-sm">
                  Update
                </a>
              </div>
              <div class="col-sm-1 mb-1">
                <a href="{% url 'crud_app:delete' pk=movie.pk %}" title="delete" class="btn btn-outline-danger btn-sm">
                  Delete
                </a>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  {% endfor %}
</div>

{% endblock %}

movies/crud_app/templates/crud_app/movies_update_form.html
{% extends "base.html" %}

{% block title %}
  <title>Update</title>
{% endblock %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    <input type="text" name='name' class='register-input' id="id_name" value="{{ movies.name }}">
    <textarea name="description" id="id_description" rows="8" cols="80">{{ movies.description }}</textarea>
    <input type="text" name='gener' class='register-input' id="id_gener" value="{{ movies.gener }}">
    <input type="text" name='director' class='register-input' id="id_director" value="{{ movies.director }}">
    <input type="submit" value="Add" class='register-button' class="btn btn-primary btn-large">
  </form>
{% endblock %}

movies/crud_app/templates/movies_list.html
{% extends "base.html" %}

{% block content %}
  {% for movie in movies_list %}
    <a href="{% url 'crud_app:single' pk=movie.pk %}">@{{movie.name}}</a>
  {% endfor %}
{% endblock %}

movies/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Movies</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Mansalva&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'movies/css/master.css' %}">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a href="{% url 'crud_app:all' %}"><button type="button" class='btn btn-outline-success my-2 my-sm-0 mr-sm-2'>CRUD Movies</button></a>
        {% if user.is_authenticated %}
          <ul class="navbar-nav mr-auto">
            <li class="nav-item"><a class="nav-link" href="{% url 'crud_app:create' %}"><button type="button" class="btn btn-outline-info">Add Movie</button></a></li>
          </ul>
          <a class="nav-link text-warning"><h5>Welcome: @{{ user.username }}</h5></a>
          <form action="{% url 'crud_app:search' %}" method="GET" class="form-inline">
            <input name='q' class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 mr-sm-2" type="submit">Search</button>
          </form>
          <a href="{% url 'accounts:logout' %}"><button type="button" class="btn btn-outline-danger">Log Out</button></a>
        {% else %}
          <ul class="navbar-nav mr-auto"></ul>
          <a href="{% url 'accounts:login' %}"><button type="button" class="btn btn-outline-primary my-2 my-sm-0 mr-sm-2">Log In</button></a>
          <a href="{% url 'accounts:signup' %}"><button type="button" class="btn btn-outline-danger">Sign Up</button></a>
        {% endif %}
      </div>
    </nav>
    <div class="container">
      <p></p>
      {% block content %}

      {% endblock %}
    </div>
    <canvas id="canvas"></canvas>

  </body>
  <script type="text/javascript" src="{% static 'movies/js/master.js' %}"></script>
</html>

movies/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron">
  <h1 class="display-4 myfont">Welcome to your movies page!</h1>
  <hr class="my-4">
  <p class='myfont'>If you are a new user, register please </p>
  <a href="{% url 'accounts:signup' %}"><button type="button" class="btn btn-danger" href="{% url 'accounts:signup' %}">Sign Up</button></a>
</div>
{% endblock %}

movies/templates/search.html
{% extends "base.html" %}

{% block content %}

<div class="accordion" id="accordionExec">
  {% for movie in movies_s %}
    <div class="card border-info">
      <div class="card-header border-warning" id="heading{{movie.pk}}">
        <h2 class="mb-0">
          <button class="btn btn-link text-info" type="button" data-toggle="collapse" data-target="#collapse{{movie.pk}}" aria-expanded="false" aria-controls="collapse{{movie.pk}}">
            {{ movie.name }}
          </button>
        </h2>
      </div>
      <div id="collapse{{movie.pk}}" class="collapse" aria-labelledby="heading{{movie.pk}}" data-parent="#accordionExec">
        <div class="card-body text-info">
          <form>
            <div class="form-inline">
              <div class="col-sm-9">
                {{ movie.description }}
              </div>
              <div class="col-sm-1 mb-1">
                <a href="{% url 'crud_app:detail' pk=movie.pk %}" title="detail" class="btn btn-outline-success btn-sm">
                  Detail
                </a>
              </div>
              <div class="col-sm-1 mb-1">
                <a href="{% url 'crud_app:movie_edit' pk=movie.pk %}" title="update" class="btn btn-outline-primary btn-sm">
                  Update
                </a>
              </div>
              <div class="col-sm-1 mb-1">
                <a href="{% url 'crud_app:delete' pk=movie.pk %}" title="delete" class="btn btn-outline-danger btn-sm">
                  Delete
                </a>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  {% endfor %}
</div>

{% endblock %}

movies/templates/test.html
{% extends "base.html" %}
{% block content %}
<h1>Now you are logged!!</h1>
{% endblock %}

movies/templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>Thanks for visiting, come back soon!</h1>
{% endblock %}